/**
 * The write allowlist for the blog repository.
 *
 * This is a security boundary, not a formatting helper. The local backend it
 * replaces handed the extension an absolute filesystem path and accepted the
 * same string back verbatim; a Vercel service that did the same would let any
 * caller name the file that gets committed. Git Data tree entries take their
 * path raw, so `../` is not even needed — `_config.yml` or
 * `.github/workflows/build-and-deploy.yml` would be enough to take over the
 * site, and that workflow holds secrets.
 *
 * So: clients address drafts by an opaque id, never by path, and every path
 * that reaches a commit goes through `assertWritablePath` first.
 *
 * The one non-obvious rule is that a safe-character allowlist is wrong here.
 * Real filenames in this repo contain spaces and colons — `2025-06-20-on AI.md`,
 * `2026-08-01-Tech Digest: Summer 2026 ... copy.md` — so `[A-Za-z0-9._-]+`
 * would reject every existing draft. The rule is "no separators, no dot-dot".
 */

import { Buffer } from 'node:buffer';
import { HttpError } from './http.js';
import { frontMatterTitle, isCuratedInsights } from './markdown.js';
import type { DraftRef } from './types.js';

export const DRAFTS_DIR = '_drafts';
export const POSTS_DIR = '_posts';

/** Base64url, unpadded. Anything else cannot have come from `encodeDraftId`. */
const BASE64URL = /^[A-Za-z0-9_-]+$/;

/** Separators, NUL and other control bytes, `%` (rejected, never decoded). */
const DANGEROUS = /[/\\%\u0000-\u001f\u007f]/;

/**
 * Paths that must never be written even if some future rule would otherwise
 * admit them. Checked case-insensitively: the allowlist below is already exact,
 * so this exists purely to fail loudly if the allowlist is ever loosened.
 */
const FORBIDDEN_PREFIXES = [
  '.github/',
  '_config',
  'gemfile',
  '_layouts/',
  '_includes/',
  'assets/',
  'scripts/',
];

const WRITABLE_PATHS = [
  // Drafts keep `.markdown` because legacy files in the repo use it.
  /^_drafts\/[^/\\]+\.(md|markdown)$/,
  // New posts are always generated by `postPathFor`, so `.md` only.
  /^_posts\/[^/\\]+\.md$/,
];

function badRequest(message: string, code: string): HttpError {
  return new HttpError(400, message, code);
}

/** base64url of the FILENAME. Never a path — the directory is server-side. */
export function encodeDraftId(filename: string): string {
  return Buffer.from(filename, 'utf8').toString('base64url');
}

/**
 * Resolve an opaque id back to a bare filename.
 *
 * Callers must still confirm the filename against a freshly fetched `_drafts/`
 * listing; this only guarantees the string cannot escape a directory.
 */
export function decodeDraftId(id: string): string {
  if (typeof id !== 'string' || id === '') {
    throw badRequest('Missing draft id', 'bad_draft_id');
  }
  if (!BASE64URL.test(id)) {
    throw badRequest('Malformed draft id', 'bad_draft_id');
  }

  const filename = Buffer.from(id, 'base64url').toString('utf8');

  // Buffer decoding is lenient — it silently skips bytes it cannot use, so a
  // mangled id would otherwise decode to a *different* valid filename.
  // Requiring the id to be the canonical encoding closes that.
  if (encodeDraftId(filename) !== id) {
    throw badRequest('Malformed draft id', 'bad_draft_id');
  }

  assertBareFilename(filename, 'bad_draft_id');
  return filename;
}

function assertBareFilename(filename: string, code: string): void {
  if (filename === '') {
    throw badRequest('Empty draft filename', code);
  }
  if (DANGEROUS.test(filename)) {
    throw badRequest('Draft filename must not contain a path separator', code);
  }
  if (filename.includes('..')) {
    throw badRequest('Draft filename must not contain ".."', code);
  }
  if (!/\.(md|markdown)$/.test(filename)) {
    throw badRequest('Draft filename must end in .md or .markdown', code);
  }
}

/** Hard gate shared by flush AND publish. Throws on anything outside _drafts/ or _posts/. */
export function assertWritablePath(path: string): void {
  if (typeof path !== 'string' || path === '') {
    throw badRequest('Missing path', 'bad_path');
  }
  if (DANGEROUS.test(path.replace(/\//g, ''))) {
    throw badRequest('Path contains an illegal character', 'bad_path');
  }
  if (path.includes('..')) {
    throw badRequest('Path must not contain ".."', 'bad_path');
  }

  const lower = path.toLowerCase();
  if (FORBIDDEN_PREFIXES.some((prefix) => lower.startsWith(prefix))) {
    throw badRequest(`Refusing to write ${path}`, 'forbidden_path');
  }

  if (!WRITABLE_PATHS.some((pattern) => pattern.test(path))) {
    throw badRequest(`Refusing to write ${path}`, 'forbidden_path');
  }
}

/**
 * Title -> URL slug.
 *
 * Jekyll's default slugify keeps commas and preserves case, so a filename with
 * spaces and colons builds fine but produces a URL like
 * `/2026/06/Tech-Digest-Summer-2026-...,-AI-Agents,-and-Go-Tooling`. Emitting a
 * kebab slug up front is what stops the next round of fix-up renames.
 */
export function slugify(title: string): string {
  const slug = (typeof title === 'string' ? title : '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    // Apostrophes join words rather than separating them: "doesn't" -> "doesnt".
    .replace(/['\u2018\u2019]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
    .replace(/-+$/, '');

  if (slug === '') {
    throw badRequest('Title produces an empty slug', 'bad_title');
  }
  return slug;
}

/**
 * The destination for a publish. Server-constructed, never client-supplied.
 *
 * No file in the repo carries a `date:` front-matter field, so this prefix is
 * the only source of a post's date — and renaming a published file changes its
 * URL. Date parts are read in UTC so the same title never lands on two
 * different days depending on where the function ran.
 */
export function postPathFor(title: string, date: Date): string {
  return `${POSTS_DIR}/${datePrefix(date, 'publish')}-${slugify(title)}.md`;
}

/**
 * The destination for a NEW draft, built from the same two ingredients as a
 * post: a UTC date prefix and a kebab slug.
 *
 * Existing drafts in this repo carry spaces and colons (`2025-06-20-on AI.md`)
 * and the write allowlist still accepts them, but nothing generated here should
 * add to that pile: Jekyll's own slugify keeps commas and case, which is what
 * produced the eight fix-up renames in the blog's history. `.md`, never
 * `.markdown` — the legacy extension is read, not written.
 */
export function draftPathFor(title: string, date: Date): string {
  return `${DRAFTS_DIR}/${datePrefix(date, 'draft')}-${slugify(title)}.md`;
}

/** `YYYY-MM-DD` in UTC. `what` only names the operation in the error message,
 *  so a rejected date reads the same way it always did on the publish path. */
function datePrefix(date: Date, what: 'publish' | 'draft'): string {
  const ms = date instanceof Date ? date.getTime() : Number.NaN;
  if (!Number.isFinite(ms)) {
    throw badRequest(`Invalid ${what} date`, 'bad_date');
  }
  const yyyy = date.getUTCFullYear();
  const mm = String(date.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(date.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

/**
 * A client-supplied `YYYY-MM-DD`, and it has to be the date it claims to be:
 * `Date.UTC` rolls `2026-02-31` forward into March, and the file would then
 * carry a date prefix the user never asked for — which for a post is its URL.
 * `undefined` means "today", read in UTC for the same reason `datePrefix` is.
 *
 * `_lib/publish.ts` still applies this rule through a private copy; it is
 * exported here so the next caller — and eventually that one — shares it rather
 * than re-deriving which invalid dates JavaScript silently accepts.
 */
export function parseIsoDate(raw: string | undefined): Date {
  if (raw === undefined) return new Date();
  const parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(raw);
  if (parts === null) {
    throw badRequest('date must be formatted YYYY-MM-DD', 'bad_date');
  }
  const [year, month, day] = [Number(parts[1]), Number(parts[2]), Number(parts[3])];
  const date = new Date(Date.UTC(year, month - 1, day));
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    throw badRequest(`No such date: ${raw}`, 'bad_date');
  }
  return date;
}

/**
 * Describe a `_drafts/` entry for the client.
 *
 * `content` is null when listing without fetching each file; the title then
 * falls back to the filename and `curated` is reported false rather than
 * guessed. Note `_drafts/2025-06-20-on AI.md` has no front matter at all.
 */
export function draftRefFromFile(filename: string, content: string | null): DraftRef {
  const title = content !== null ? frontMatterTitle(content) : null;
  return {
    id: encodeDraftId(filename),
    filename,
    path: `${DRAFTS_DIR}/${filename}`,
    title: title !== null && title.trim() !== '' ? title : filename,
    curated: content !== null ? isCuratedInsights(content) : false,
  };
}
